export const ADD_ITEM = {
  START: "ADD_ITEM_START",
  CANCEL: "ADD_ITEM_CANCEL",
  ERROR: "ADD_ITEM_ERROR",
  SUCCESS: "ADD_ITEM_SUCCESS"
};

export const SEARCH_ITEM = {
  START: "SEARCH_ITEM_START",
  CANCEL: "SEARCH_ITEM_CANCEL",
  ERROR: "SEARCH_ITEM_ERROR",
  SUCCESS: "SEARCH_ITEM_SUCCESS"
};

export const FILTER_ITEM = `FILTER_ITEM`

export const RESET = "RESET";
