export const ADD_ITEM = "ADD_ITEM";

export const SEARCH_ITEM = {
	START: "SEARCH_ITEM_START",
	CANCEL: "SEARCH_ITEM_CANCEL",
	ERROR: "SEARCH_ITEM_ERROR",
	SUCCESS: "SEARCH_ITEM_SUCCESS"
};

export const FILTER_ITEM = `FILTER_ITEM`;
export const DELETE_ITEM = `DELETE_ITEM`;
export const UPDATE_ITEM = `UPDATE_ITEM`;
export const GET_ITEM = `GET_ITEM`;
export const OPEN_MODAL = `OPEN_MODAL`;
export const CLOSE_MODAL = `CLOSE_MODAL`;
export const FORM_CONTROL_CHANGE = `FORM_CONTROL_CHANGE`;
export const SEARCH_QUERY_CHANGE = `SEARCH_QUERY_CHANGE`;
export const UPDATE_FAVOURITE_ITEM = `UPDATE_FAVOURITE_ITEM`;

export const RESET = "RESET";
